trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'